import json
from datetime import datetime

def generate_report(target_url, vulnerabilities):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    total = len(vulnerabilities)
    high = len([v for v in vulnerabilities if v["severity"] == "High"])
    medium = len([v for v in vulnerabilities if v["severity"] == "Medium"])
    low = len([v for v in vulnerabilities if v["severity"] == "Low"])

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Scan Report - {target_url}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; background: #f4f4f4; }}
        h1 {{ color: #2c3e50; }}
        .summary {{ display: flex; gap: 20px; margin: 20px 0; }}
        .card {{ padding: 20px; border-radius: 8px; color: white; min-width: 100px; text-align: center; }}
        .card h2 {{ margin: 0; font-size: 36px; }}
        .card p {{ margin: 5px 0 0; font-size: 14px; }}
        .total {{ background: #2c3e50; }}
        .high {{ background: #e74c3c; }}
        .medium {{ background: #e67e22; }}
        .low {{ background: #27ae60; }}
        table {{ width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; }}
        th {{ background: #2c3e50; color: white; padding: 12px; text-align: left; }}
        td {{ padding: 12px; border-bottom: 1px solid #ddd; }}
        .badge {{ padding: 4px 10px; border-radius: 4px; color: white; font-size: 12px; font-weight: bold; }}
        .High {{ background: #e74c3c; }}
        .Medium {{ background: #e67e22; }}
        .Low {{ background: #27ae60; }}
        .footer {{ margin-top: 30px; color: #888; font-size: 13px; }}
    </style>
</head>
<body>
    <h1>Web Vulnerability Scan Report</h1>
    <p><strong>Target:</strong> {target_url}</p>
    <p><strong>Scan Time:</strong> {timestamp}</p>

    <div class="summary">
        <div class="card total"><h2>{total}</h2><p>Total Issues</p></div>
        <div class="card high"><h2>{high}</h2><p>High</p></div>
        <div class="card medium"><h2>{medium}</h2><p>Medium</p></div>
        <div class="card low"><h2>{low}</h2><p>Low</p></div>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Vulnerability</th>
                <th>Severity</th>
                <th>Details</th>
            </tr>
        </thead>
        <tbody>
"""

    if total == 0:
        html += """
            <tr>
                <td colspan="4" style="text-align:center; color:#27ae60;">
                    No vulnerabilities found.
                </td>
            </tr>
"""
    else:
        for i, vuln in enumerate(vulnerabilities, 1):
            html += f"""
            <tr>
                <td>{i}</td>
                <td>{vuln['type']}</td>
                <td><span class="badge {vuln['severity']}">{vuln['severity']}</span></td>
                <td>{vuln['details']}</td>
            </tr>
"""

    html += f"""
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by WebVulnScanner &mdash; For authorized testing only.</p>
    </div>
</body>
</html>"""

    filename = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
    with open(filename, "w") as f:
        f.write(html)

    json_filename = filename.replace(".html", ".json")
    with open(json_filename, "w") as f:
        json.dump({
            "target": target_url,
            "timestamp": timestamp,
            "vulnerabilities": vulnerabilities
        }, f, indent=4)

    return filename, json_filename